### ISSUE TITLE
Empty attributes

### ISSUE THREAD

**Issue by NVolcz** [rejectedsoftware/diet-ng#11]
(I think) diet-ng generates "invalid" HTML for attributes equals to true:
https://github.com/rejectedsoftware/diet-ng/blob/master/source/diet/html.d#L183

See:
https://stackoverflow.com/questions/6926442/is-an-xml-attribute-without-a-value-valid

**Comment by s-ludwig** [comment]
This is valid HTML 5 syntax for Boolean attributes. See
https://www.w3.org/TR/2008/WD-html5-20080610/syntax.html#attributes1
and
https://www.w3.org/TR/2008/WD-html5-20080610/semantics.html#boolean

The unit test particularly checks that this syntax is only used for HTML 5.
