### ISSUE TITLE
Support for inderting HTML id and class dynamically

### ISSUE THREAD

**Issue by aberba** [rejectedsoftware/diet-ng#17]
I can't do:

```jade
div.#{isDone == true ? "active": "inactive";}
div.#{isDone == true ? "active": "inactive";}.selected
div##{isDone == true ? "active": "inactive";}.selected
```
Will the ## even work?
Or am i doing is wrong?

**Comment by azbukagh** [comment]
Try `div##\{isDone == true ? "active": "inactive";\}.selected`
You can read about string interpolations [here](http://vibed.org/templates/diet#string-interpolations).

**Comment by s-ludwig** [comment]
`.` and `#` are meant just as a shortcut for static names. The idiomatic notation for the example above would be `div.selected(class=isDone?"active":"inactive")` - the result will be `<div class="selected active">` for `isDone == true`.

**Comment by s-ludwig** [comment]
Instead of the explicit `div.selected`, in this case just `.selected` will also have the same effect.

**Comment by aberba** [comment]
Thanks. Never thought of it that way.
