### ISSUE TITLE
Attributes: falsy code evaluation shouldn't display the attribute

### ISSUE THREAD

**Issue by wilzbach** [rejectedsoftware/diet-ng#19]
For example with `selected` or `checked` <input... checked>` and `<input...  chechbox=false>` will both display the checkbox as "checked". 
This is a bit unintuitive as it easily leads to errors as e.g. here in the official Vibe.d examples:

https://github.com/rejectedsoftware/vibe.d/blob/master/examples/web/views/settings.dt#L11

Currently the best workaround is to introduce redundancy:

```
- if (auth.isAdmin)
    input#admin(name="admin", type="checkbox", checked)
- else
    input#admin(name="admin", type="checkbox")
```

Once I have a bit of time, I am happy to submit a PR for this. For now I just put this here in the tracker, so that it's not forgotten.

**Comment by s-ludwig** [comment]
There is actually special handling for Boolean attributes (D attribute expressions that evaluate to `bool`). If `false`, the attribute gets omitted, and if `true`, the attribute gets emitted as `checked` for HTML 5 and `checked="checked"` otherwise.

**Comment by s-ludwig** [comment]
Corresponding tests: https://github.com/rejectedsoftware/diet-ng/blob/1d55a23d0c7bbe00f45c11759a40121de273a897/source/diet/html.d#L554-L561
