### ISSUE TITLE
No newlines after tags in html

### ISSUE THREAD

**Issue by tramker** [rejectedsoftware/diet-ng#8]
I've noticed that the diet-ng doesn't output the newline characters after tags.
```
doctype html
html
  body
    div something
```
diet-ng (vibe 0.7.30-beta.1) output:
```<!DOCTYPE html><html><body><div>something</div></body></html>```

classic diet (vibe 0.7.29) output:
```
<!DOCTYPE html>
<html>
	<body>
		<div>something</div>
	</body>
</html>
```

**Comment by s-ludwig** [comment]
I started the other way around this time - the implementation in vibe.d does pretty printing, which is nice for debugging, but wastes transfer bandwidth, while diet-ng outputs as compact as possible. But the plan is definitely to add both modes to diet-ng.

**Comment by tramker** [comment]
Great, thanks.
